//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.detalle_actividad = new HashSet<detalle_actividad>();
            this.detalle_beneficio = new HashSet<detalle_beneficio>();
            this.detalle_seguro = new HashSet<detalle_seguro>();
        }
    
        public int numcontrato { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechatermino { get; set; }
        public string destino { get; set; }
        public int duraciondias { get; set; }
        public System.DateTime fechaini { get; set; }
        public System.DateTime fechaterm { get; set; }
        public string curso_idcurso { get; set; }
        public string curso_colegio_codcolegio { get; set; }
        public string ejecutivo_rutejecutivo { get; set; }
        public int destino_iddestino { get; set; }
        public int tipactividad_idtipoact { get; set; }
        public string fechapagos { get; set; }
        public int costototseguros { get; set; }
        public int costototactividades { get; set; }
        public int porctotbeneficios { get; set; }
        public int costoservicios { get; set; }
        public int meta { get; set; }
        public int tipactividad_modaporte_idmod { get; set; }
        public int curso_colegio_idtipo { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual destino destino1 { get; set; }
        public virtual ejecutivo ejecutivo { get; set; }
        public virtual tipactividad tipactividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_actividad> detalle_actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_beneficio> detalle_beneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_seguro> detalle_seguro { get; set; }
    }
}
