//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int idusuario { get; set; }
        public string apoderado_rutapoderado { get; set; }
        public string rutapoderado { get; set; }
        public string rutejecutivo { get; set; }
        public string rutadmsis { get; set; }
        public string rutdueño { get; set; }
    
        public virtual adm_sis adm_sis { get; set; }
        public virtual apoderado apoderado { get; set; }
        public virtual dueño dueño { get; set; }
        public virtual ejecutivo ejecutivo { get; set; }
    }
}
