//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int ContratoId { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public int NumeroHoras { get; set; }
        public int ValorHoraId { get; set; }
        public int AfpId { get; set; }
        public int SaludId { get; set; }
        public int BonificacionId { get; set; }
        public double SueldoBase { get; set; }
        public double SueldoLiquido { get; set; }
        public double SueldoBruto { get; set; }
    
        public virtual Afp Afp { get; set; }
        public virtual Bonificacion Bonificacion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Salud Salud { get; set; }
        public virtual ValorHora ValorHora { get; set; }
    }
}
