# Generated by Django 2.2.5 on 2019-11-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='clientes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechanamiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
