//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contrato()
        {
            this.info_actividad = new HashSet<info_actividad>();
            this.info_beneficio = new HashSet<info_beneficio>();
            this.info_seguro = new HashSet<info_seguro>();
        }
    
        public int numcontrato { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechatermino { get; set; }
        public int duraciondias { get; set; }
        public System.DateTime fechaini { get; set; }
        public System.DateTime fechaterm { get; set; }
        public string fechapagos { get; set; }
        public int costototseguros { get; set; }
        public int costototactividades { get; set; }
        public int porctotbeneficios { get; set; }
        public int costoservicios { get; set; }
        public int meta { get; set; }
        public int tipactividad_idtipoact { get; set; }
        public string curso_idcurso { get; set; }
        public int ciudad_codciudad { get; set; }
        public string usuario_rutusu { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual curso curso { get; set; }
        public virtual tipactividad tipactividad { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_actividad> info_actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_beneficio> info_beneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_seguro> info_seguro { get; set; }
    }
}
