//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cta_usuario
    {
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string nombre { get; set; }
        public string usuario_rutusu { get; set; }
        public int tipcuenta_idtipocta { get; set; }
    
        public virtual tipcuenta tipcuenta { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
