//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_actividad
    {
        public int cant_actividad { get; set; }
        public int contrato_numcontrato { get; set; }
        public int actividad_idactividad { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual contrato contrato { get; set; }
    }
}
